image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off

install:
  - java -jar ./artifacts/app-order.jar -port=7777 &
build_script:
 - chmod +x gradlew # даем права доступа к файлу gradlew
 - ./gradlew test --info  # запускаем тест, флаг --info позволяет выводить больше информации
# build_script:
  # - chmod +x gradlew
# - ./gradlew test -Dselenide.headless=true
 
